export declare function endianness(): string;
export declare function hostname(): string;
export declare function loadavg(): number[];
export declare function uptime(): number;
export declare function totalmem(): number;
export declare function freemem(): number;
export declare function cpus(): any[];
export declare function type(): string;
export declare function release(): string;
export declare function networkInterfaces(): {};
export declare function getNetworkInterfaces(): {};
export declare function arch(): string;
export declare function platform(): string;
export declare function tmpdir(): string;
export declare const EOL: string;
export declare function homedir(): string;
declare const _default: {
    endianness: typeof endianness;
    hostname: typeof hostname;
    loadavg: typeof loadavg;
    uptime: typeof uptime;
    freemem: typeof freemem;
    totalmem: typeof totalmem;
    cpus: typeof cpus;
    type: typeof type;
    release: typeof release;
    networkInterfaces: typeof networkInterfaces;
    getNetworkInterfaces: typeof getNetworkInterfaces;
    arch: typeof arch;
    platform: typeof platform;
    tmpdir: typeof tmpdir;
    EOL: string;
    homedir: typeof homedir;
};
export default _default;
